### ISSUE TITLE
按照快速开始的配置试用模型后，toys.trans文件显示全部都是unk

### ISSUE THREAD

**Issue by yanmengqi** [zhaocq-nlp/NJUNMT-tf#2]
第一个issues哈哈
我在试用您开发的模型后，toys.trans文件显示为空，其中步骤是按照快速开始中提供的参数设置的，请问这是什么问题？
程序可以一直跑下来，并没有报错。

**Comment by zhaocq-nlp** [comment]
toy数据只是用来debug的，要看结果就上大一点的数据啊。README.md里有句话：
Note: do not expect any good translation results with this toy example. Consider training on larger parallel datasets instead.
